package com.stonytark.usefultoolsmod.datagen;

import com.stonytark.usefultoolsmod.UsefultoolsMod;
import com.stonytark.usefultoolsmod.block.ModBlocks;
import net.minecraft.client.data.models.BlockModelGenerators;
import net.minecraft.client.data.models.ItemModelGenerators;
import net.minecraft.client.data.models.ModelProvider;
import net.minecraft.data.PackOutput;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.registries.DeferredHolder;

/**
 * 26.1 model generation moved from the NeoForge {@code BlockStateProvider} into the vanilla
 * {@link ModelProvider}. The actual generators are spawned by the parent's
 * {@link #registerModels} hook with {@link BlockModelGenerators} / {@link ItemModelGenerators}
 * instances. We emit a trivial cube model for every block we own so that the per-modid
 * validator inside {@code ModelProvider} doesn't trip — the existing
 * {@code src/main/resources/assets/usefultoolsmod/blockstates/} files are the authoritative
 * source at runtime; this provider just regenerates baselines for {@code runData}.
 *
 * The {@link ModelProvider} ctor takes the modid; that scopes its default
 * {@code getKnownBlocks()} stream to our namespace only.
 */
public class ModBlockStateProvider extends ModelProvider {

    public ModBlockStateProvider(PackOutput output) {
        super(output, UsefultoolsMod.MOD_ID);
    }

    @Override
    public String getName() {
        return "Block Model Definitions - " + UsefultoolsMod.MOD_ID;
    }

    /** This provider only registers blocks; standalone items are handled by
     *  {@link ModItemModelProvider}. Returning an empty item stream prevents the
     *  ModelProvider validator from demanding entries we don't emit here. */
    @Override
    protected java.util.stream.Stream<? extends net.minecraft.core.Holder<net.minecraft.world.item.Item>> getKnownItems() {
        return java.util.stream.Stream.empty();
    }

    @Override
    protected void registerModels(BlockModelGenerators blockModels, ItemModelGenerators itemModels) {
        // Cube-all entries — every block this mod registers gets a trivial cube model.
        // Item-models for the BlockItem children are auto-generated by ModelProvider's
        // ItemInfoCollector.finalizeAndValidate based on the registered block model.
        cube(blockModels, ModBlocks.RGOLDBLOCK);
        cube(blockModels, ModBlocks.HRBLOCK);
        cube(blockModels, ModBlocks.RGOLDORE);
        cube(blockModels, ModBlocks.SEMBLOCK);
        cube(blockModels, ModBlocks.SOBLOCK);
        cube(blockModels, ModBlocks.LBLOCK);
        cube(blockModels, ModBlocks.RGOLD_NETHER_ORE);
        cube(blockModels, ModBlocks.RGOLD_END_ORE);
        cube(blockModels, ModBlocks.RGOLD_DEEPSLATE_ORE);
        cube(blockModels, ModBlocks.HGLOW_BLOCK);
        cube(blockModels, ModBlocks.RAW_RGOLD_BLOCK);
        cube(blockModels, ModBlocks.ECTOPLASM_BLOCK);
        cube(blockModels, ModBlocks.REFINED_ECTOPLASM_BLOCK);
        cube(blockModels, ModBlocks.HARDENED_COAL_BLOCK);
        cube(blockModels, ModBlocks.COAL_DUST_BLOCK);
        cube(blockModels, ModBlocks.OBSHARD_BLOCK);
        cube(blockModels, ModBlocks.CALCIFIED_AMETHYST_BLOCK);
        cube(blockModels, ModBlocks.GLACIAL_SHARD_BLOCK);
        cube(blockModels, ModBlocks.POLISHED_QUARTZ_BLOCK);
        cube(blockModels, ModBlocks.POLISHED_PRISMARINE_BLOCK);

        // SpectralInfuser is intentionally NOT emitted here. Its blockstate + both
        // orientable_with_bottom block models (lit / not-lit variants for all 4 facings)
        // live as hand-written JSON under src/main/resources/assets/usefultoolsmod/, where
        // the data-gen can't clobber them. ModelProvider's validator stays quiet because
        // we override getKnownBlocks() below to elide the entry.
    }

    /** Drop SpectralInfuser from the per-mod validator stream so it doesn't demand a
     *  generated model for the block whose model ships hand-written under
     *  {@code src/main/resources/}. */
    @Override
    protected java.util.stream.Stream<? extends net.minecraft.core.Holder<Block>> getKnownBlocks() {
        return super.getKnownBlocks().filter(holder -> holder.value() != ModBlocks.SPECTRAL_INFUSER.get());
    }

    private static void cube(BlockModelGenerators blockModels, DeferredHolder<Block, Block> block) {
        blockModels.createTrivialCube(block.get());
    }
}
